mysite/account/urls.py
#enconding=utf-8
from django.conf.urls import url
from . import views
# from django.contrib.auth.views import LoginView


app_name='account'
urlpatterns = [
    url(r"^login/$", views.user_login, name="user_login"),
    url(r"^register/$", views.register, name="user_register"),
    url(r"^my-information/$", views.myself, name="my_information"),
    url(r"^edit-my-information/$", views.myself_edit, name="edit_my_information"),
]

mysite/blog/urls.py
#enconding=utf-8
from django.conf.urls import url
from . import views

app_name='blog'
urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    # views.blog_article 也可以写成"views.blog_article",两种写法没有什么区别，只要保证在同一个项目中保持一致即可
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog")),
    path(r'account/', include('account.urls', namespace='account')),
]

mysite/account/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=20, null=True)

    def __str__(self):
        return "user {}".format(self.user.username)

class UserInfo(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)
    # blank=True 该参数表示该参数可以为空
    school = models.CharField(max_length=20, blank=True)
    company = models.CharField(max_length=100, blank=True)
    profession = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=100, blank=True)
    aboutme = models.TextField(blank=True)

    def __str__(self):
        return "user:{}".format(self.user.username)

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class BlogArticles(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-publish',)    # 这里传入的参数是元组，所以只有一个元素的时候后面的“，”也不能少了
    def __str__(self):
        return self.title

mysite/account/forms.py
#enconding=utf-8
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile,UserInfo

# 登录表单
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

# 注册表单
class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    """
        1.Meta(单词一定要拼写正确)是RegistrationForm的一个内部类
        2.RegistrationForm()对象有很多的属性，例如：['as_p', 'fields',...] 可通过dir(RegistrationForm())来查看
        3.可以通过该内部类来修改属性值，例如：fields = ("username", "email")
    """
    class Meta:
        # 设置model（单词拼写要正确）值，可以理解为引用已有的model即User
        model = User
        fields = ("username", "email")
        # fields = "__all__"

    def clean_password2(self):
        cd = self.data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("password do not match!")
        return cd["password2"]


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'birth')


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ('school', 'company', 'profession', 'address', 'aboutme')

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email",)

mysite/account/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import UserInfo, UserProfile
from .forms import LoginForm,RegistrationForm,UserProfileForm,UserForm,UserInfoForm

# Create your views here.
# 个人信息编辑
@login_required(login_url='../login/')
def myself_edit(request):
    user = User.objects.get(username=request.user.username)
    userprofile = UserProfile.objects.get(user=request.user)
    userinfo = UserInfo.objects.get(user=request.user)

    if request.method == 'POST':
        user_from = UserForm(request.POST)
        userprofile_from = UserProfileForm(request.POST)
        userinfo_from = UserInfoForm(request.POST)
        print("request.POST:{}".format(request.POST))
        if user_from.is_valid() or userprofile_from.is_valid() or userinfo_from.is_valid():
            print("*****")
            user_cd = user_from.data
            userprofile_cd = userprofile_from.data
            userinfo_cd = userinfo_from.data
            user.email=user_cd['email']
            userprofile.birth = userprofile_cd['birth']
            userprofile.phone = userprofile_cd['phone']
            userinfo.school = userinfo_cd['school']
            userinfo.company = userinfo_cd['company']
            userinfo.profession = userinfo_cd['profession']
            userinfo.address = userinfo_cd['address']
            userinfo.aboutme = userinfo_cd['aboutme']
            user.save()
            userprofile.save()
            userinfo.save()
        return HttpResponseRedirect('../my-information')
    else:
        user_form = UserForm(instance=request.user)
        userprofile_form = UserProfileForm(initial={"birth":userprofile.birth, "phone":userprofile.phone})
        userinfo_form = UserInfoForm(initial={"school":userinfo.school, "company":userinfo.company, "profession":userinfo.profession, "address":userinfo.address, "aboutme":userinfo.aboutme})
        return render(request,'account/myself_edit.html', {"user_form":user_form, "userprofile_form":userprofile_form, "userinfo_form":userinfo_form})
# 个人信息展示页面
@login_required(login_url="../login")   # 只有登录才能看到，如果没有登录则指向登录页面
def myself(request):
    user = User.objects.get(username=request.user.username)
    userprofile = UserProfile.objects.get(user=user)
    userinfo = UserInfo.objects.get(user=user)
    return render(request, "account/myself.html", {"user":user, "userprofile":userprofile, "userinfo":userinfo})


# 登录方法
def user_login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user:
                login(request, user)
                # 地址的重定向都是在原有的地址基础上拼接上参数中的地址来实现的
                return HttpResponseRedirect("../my-information")
            else:
                return HttpResponse("Sorry. your username or password is not right")

        else:
            return HttpResponse("Invalid login")

    if request.method == "GET":
        login_form = LoginForm()
        return render(request, "account/login.html", {"form":login_form})

def register(request):
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        userprofile_form = UserProfileForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.data["password"])
            new_user.save()
            new_profile = userprofile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            UserInfo.objects.create(user=new_user)
            return HttpResponse("successfully")
        else:
            return HttpResponse("sorry, you can not register")
    else:
        user_form = RegistrationForm()
        user_profile = UserProfileForm()
        return render(request, "account/register.html", {"form":user_form, "profile":user_profile})

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogArticles

# Create your views here.
def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, "blog/titles.html", {"blogs":blogs})

def blog_article(request, article_id):
    # article = BlogArticles.objects.get(id=article_id)
    article = get_object_or_404(BlogArticles, id=article_id)
    pub = article.publish
    return render(request, "blog/content.html", {"article":article, "pub":pub})

mysite/blog/templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="http://necolas.github.io/normalize.css">
    <link rel="stylesheet" href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootsrap/3.0.3/js/bootstrap.min.js"></script>
</body>
</html>

mysite/blog/templates/blog/content.html
{% extends "base.html" %}
{% block title %}blog article{% endblock %}
{% block content %}
<div class="row text-content vertical-middle-sm">
    <h1>{{ article.title }}</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <p class="text-content">
            <span>{{ article.author.username }}</span>
            <span style="margin-left:20px">{{ pub}}</span>
        </p>
     <div>{{ article.body }}</div>
    </div>
</div>
{% endblock %}

mysite/blog/templates/blog/titles.html
{% extends "base.html" %}
{% block title %}block titles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>我的博客</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <ul>
            {% for blog in blogs %}
            <li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
 {% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'}">
    <!--
    <link rel="stylesheet" href="http://necolas.github.io/normalize.css">
    <link rel="stylesheet" href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css">-->
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
    <!--
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootsrap/3.0.3/js/bootstrap.min.js"></script>-->
</body>
</html>

mysite/templates/blog/content.html
{% extends "base.html" %}
{% block title %}blog article{% endblock %}
{% block content %}
<div class="row text-content vertical-middle-sm">
    <h1>{{ article.title }}</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <p class="text-content">
            <span>{{ article.author.username }}</span>
            <span style="margin-left:20px">{{ pub}}</span>
        </p>
     <div>{{ article.body }}</div>
    </div>
</div>
{% endblock %}

mysite/templates/blog/titles.html
{% extends "base.html" %}
{% block title %}block titles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>我的博客</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <ul>
            {% for blog in blogs %}
            <li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
 {% endblock %}

mysite/templates/footer.html
<div class="container">
    <hr>
    <p class="text-conter">copy right www.itdiffer.com</p>
</div>

mysite/templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <a class="navbar-brand" href="http://www.itdiffer.com">
            <img src="{% static '/images/logo.png' %}" width="100px">
        </a>
    </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
            </ul>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
            </ul>
        </div>
    </nav>
</div>

mysite/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test html</title>
</head>
<body>
    <tr>
        <th>
            <label for="id_username">Username:</label>
        </th>
        <td>
            <input type="text" name="username" required id="id_username">
        </td>
    </tr>
    <tr>
        <th>
            <label for="id_password">Password:</label>
        </th>
        <td>
            <input type="password" name="password" required id="id_password">
        </td>
    </tr>
</body>
</html>